import { Timestamp } from "firebase/firestore";
import { RequestForm } from "../../../interfaces";

export const DummyData: RequestForm[] = [
  {
    email: "test@gmail.com",
    name: "test1",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test2",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test3",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test4",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test5",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test6",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test7",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test8",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test9",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test10",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test11",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test12",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test13",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test14",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
  {
    email: "test@gmail.com",
    name: "test15",
    ssn: "19990917-1234",
    period: "6",
    gender: "male",
    afMember: "yes",
    payMethod: "cash",
    regDate: Timestamp.now(),
    hasPaid: "yes",
  },
];
